find_program(SCCACHE_EXECUTABLE sccache QUIET)
find_program(CCACHE_EXECUTABLE ccache QUIET)

option(ENABLE_CCACHE "Enable ccache support" ON)
if(ENABLE_CCACHE)
  if(SCCACHE_EXECUTABLE)
    message(STATUS "Using sccache: ${SCCACHE_EXECUTABLE}")
    set(CMAKE_C_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}")
  elseif(CCACHE_EXECUTABLE)
    message(STATUS "Using scache: ${CCACHE_EXECUTABLE}")
    set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}")
  else()
    message(WARNING "ccache or sccache not found, disabling ccache support")
  endif()
endif()
