file(TO_CMAKE_PATH "${CMAKEFORMAT_ROOT_DIR}" CMAKE_FORMAT_ROOT_DIR)
set(CMAKEFORMAT_ROOT_DIR
    "${CMAKEFORMAT_ROOT_DIR}"
    CACHE PATH "Path to search for cmake-format")

if(CMAKEFORMAT_ROOT_DIR)
  find_program(
    CMAKEFORMAT_EXECUTABLE
    NAMES cmake-format
    PATHS "${CMAKEFORMAT_ROOT_DIR}"
    NO_DEFAULT_PATH)
endif()

find_program(CMAKEFORMAT_EXECUTABLE NAMES cmake-format)

if(CMAKEFORMAT_EXECUTABLE)
  execute_process(
    COMMAND "${CMAKEFORMAT_EXECUTABLE}" --version
    OUTPUT_VARIABLE CMAKEFORMAT_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  string(REGEX REPLACE "([0-9]+\\.([0-9]+\\.[0-9]+)?)" "\\1" CMAKEFORMAT_VERSION
                       "${CMAKEFORMAT_VERSION}")
endif()

find_package(PackageHandleStandardArgs REQUIRED)
find_package_handle_standard_args(
  CmakeFormat
  REQUIRED_VARS CMAKEFORMAT_EXECUTABLE
  VERSION_VAR CMAKEFORMAT_VERSION)

if(CMAKEFORMAT_FOUND OR CMAKE_FORMAT_MARK_AS_ADVANCED)
  mark_as_advanced(CMAKEFORMAT_ROOT_DIR)
endif()

mark_as_advanced(CMAKEFORMAT_EXECUTABLE)
