
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: 'Windows - MSVC', os: windows-latest, cc: 'cl', cxx: 'cl'}
          - { name: 'Ubuntu - GCC', os: ubuntu-latest, cc: 'gcc', cxx: 'g++' }
          - { name: 'MacOS - Clang', os: macos-latest, cc: 'clang', cxx: 'clang++' }
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Dependencies (Windows)'
        if: matrix.config.os == 'windows-latest'
        run: |
          choco install ninja
      - name: 'Install Dependencies (Linux)'
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cppcheck clang-tidy
          pip install cmakelang gcovr
      - name: 'Install Dependencies (MacOS)'
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install ninja
      - name: 'Create Build Environment'
        shell: bash
        run: |
          cmake -E make_directory ${{ github.workspace }}/build
      - name: 'Configure Cmake'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -G Ninja
      - name: 'Build'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Debug
      - name: 'Test'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest -C Debug
